services:
  - type: web
    name: runningtunes-frontend
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    rootDir: .
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://runningtunes-backend.onrender.com
    plan: free
